import { strToU8, zipSync } from "fflate";
import type { GeneratedProject, ProjectQualityReport } from "@/lib/project-types";

function projectReadme(project: GeneratedProject): string {
  return `# ${project.spec.name}

This is a standalone crypto product generated by Drops Studio.

## Run locally

Open \`index.html\` directly, or serve this folder with \`npx serve .\`.

## Foundation

- DropsTab is the market data, research and context layer.
- Drops Bot is the alert, Telegram and approved action handoff layer.
- Live requests use the public data adapter in \`project.json\`.
- No AI or product API key is bundled in this export.

## Deploy

The package works on Vercel, Cloudflare Pages, Netlify and GitHub Pages with the included files.
`;
}

export function buildProjectArchiveFiles(project: GeneratedProject, quality: ProjectQualityReport, gameAsset?: Uint8Array): Record<string, Uint8Array> {
  const slug = project.spec.slug;
  const integrationManifest = {
    schemaVersion: 1,
    data: { provider: "DropsTab Public API", endpoint: project.spec.dataEndpoint, polling: false, sharedCacheSeconds: 900 },
    actions: { provider: "Drops Bot", mode: "guided official handoff", automaticExecution: false },
    ai: { provider: project.spec.brain.provider, model: project.spec.brain.model, keyIncluded: false },
  };
  const files: Record<string, Uint8Array> = {
    "index.html": strToU8(project.html),
    "README.md": strToU8(projectReadme(project)),
    "project.json": strToU8(JSON.stringify(project.spec, null, 2)),
    "quality-report.json": strToU8(JSON.stringify(quality, null, 2)),
    "drops.config.json": strToU8(JSON.stringify(integrationManifest, null, 2)),
    "tests/smoke.mjs": strToU8(`import assert from "node:assert/strict";\nimport { readFile } from "node:fs/promises";\nconst html = await readFile(new URL("../index.html", import.meta.url), "utf8");\nassert.match(html, /data-project-kind="${project.spec.presetId}"/);\nassert.match(html, /DropsTab/);\nassert.match(html, /Drops Bot/);\nassert.doesNotMatch(html, /\\beval\\s*\\(|new Function/);\nconsole.log("Drops Studio smoke checks passed");\n`),
    "vercel.json": strToU8(JSON.stringify({ cleanUrls: true, trailingSlash: false }, null, 2)),
    "netlify.toml": strToU8(`[build]\n  publish = "."\n\n[[headers]]\n  for = "/*"\n  [headers.values]\n    X-Content-Type-Options = "nosniff"\n`),
    "wrangler.toml": strToU8(`name = "${slug}"\ncompatibility_date = "2026-07-28"\n[assets]\ndirectory = "."\n`),
    ".github/workflows/pages.yml": strToU8(`name: Deploy static site to Pages\non:\n  push:\n    branches: [main]\n  workflow_dispatch:\npermissions:\n  contents: read\n  pages: write\n  id-token: write\njobs:\n  deploy:\n    environment:\n      name: github-pages\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/configure-pages@v5\n      - uses: actions/upload-pages-artifact@v3\n        with:\n          path: .\n      - uses: actions/deploy-pages@v4\n`),
  };
  if (project.spec.presetId === "crypto-game" && gameAsset?.length) {
    files["assets/market-catcher-retro.png"] = gameAsset;
  }
  return files;
}

export function createProjectArchive(project: GeneratedProject, quality: ProjectQualityReport, gameAsset?: Uint8Array): Uint8Array {
  return zipSync(buildProjectArchiveFiles(project, quality, gameAsset), { level: 6 });
}
