import { strToU8, zipSync } from "fflate";
import { getProductReality } from "./product-reality.ts";
import type { GeneratedProject, ProjectQualityReport } from "@/lib/project-types";

function projectReadme(project: GeneratedProject): string {
  const reality = getProductReality(project.spec.presetId);
  return `# ${project.spec.name}

This is a runnable crypto product generated by Drops Studio.

## Reality contract

- Delivery mode: ${reality.deliveryMode}
- Deliverable: ${reality.deliverable}
- Works now: ${reality.worksNow.join("; ")}
- Still requires: ${reality.requires.join("; ")}

Publishing this web app does not claim that an external Telegram channel, wallet feed, trade, community backend or scheduled job exists. Those outcomes are marked pending until their provider verifies them.

## Run locally

Open \`index.html\` directly, or serve this folder with \`npx serve .\`. Deploying to Vercel also enables the included session-only Telegram verification function.

## Foundation

- DropsTab is the market data, research and context layer.
- Drops Bot is the alert, Telegram and approved action handoff layer; official setup is completed in Telegram.
- Live requests use the public data adapter in \`project.json\`.
- No AI or product API key is bundled in this export.

## Deploy

The browser product works on Vercel, Cloudflare Pages, Netlify and GitHub Pages. The included Vercel API function lets a user verify their own BotFather bot and send a real test post without storing the token.
`;
}

const telegramFunction = `const attempts = new Map();
function reply(res, status, body) { res.setHeader("cache-control", "no-store"); res.setHeader("access-control-allow-origin", "*"); res.setHeader("access-control-allow-headers", "content-type, x-drops-session"); res.status(status).json(body); }
async function call(token, method, body) {
  const response = await fetch("https://api.telegram.org/bot" + token + "/" + method, { method: body ? "POST" : "GET", headers: body ? { "content-type": "application/json" } : {}, body: body ? JSON.stringify(body) : undefined });
  const payload = await response.json().catch(() => null);
  if (!response.ok || !payload?.ok) throw new Error("Telegram verification failed");
  return payload.result;
}
export default async function handler(req, res) {
  if (req.method === "OPTIONS") { res.setHeader("access-control-allow-origin", "*"); res.setHeader("access-control-allow-methods", "POST, OPTIONS"); res.setHeader("access-control-allow-headers", "content-type, x-drops-session"); return res.status(204).end(); }
  if (req.method !== "POST") return reply(res, 405, { error: "Method not allowed" });
  const key = String(req.headers["x-vercel-forwarded-for"] || req.headers["x-drops-session"] || crypto.randomUUID()).split(",")[0]; const now = Date.now(); const current = attempts.get(key);
  if (!current || current.resetAt < now) attempts.set(key, { count: 1, resetAt: now + 3600000 }); else if (++current.count > 12) return reply(res, 429, { error: "Too many checks" });
  const token = String(req.body?.token || "").trim(); const channel = String(req.body?.channel || "").trim(); const message = String(req.body?.message || "").trim().slice(0, 2000); const sendTest = req.body?.sendTest === true;
  if (!/^\\d{6,12}:[A-Za-z0-9_-]{30,}$/.test(token)) return reply(res, 400, { error: "Enter a valid BotFather token" });
  if (!/^@[A-Za-z][A-Za-z0-9_]{4,31}$/.test(channel) && !/^-100\\d{6,20}$/.test(channel)) return reply(res, 400, { error: "Enter @channelusername or -100 channel ID" });
  try {
    const bot = await call(token, "getMe"); const chat = await call(token, "getChat", { chat_id: channel }); const member = await call(token, "getChatMember", { chat_id: chat.id, user_id: bot.id });
    if (!["creator", "administrator"].includes(member.status) || member.can_post_messages === false) return reply(res, 409, { error: "Bot needs channel admin post permission" });
    if (sendTest && !message) return reply(res, 400, { error: "Add a test message before sending" });
    const sent = sendTest ? await call(token, "sendMessage", { chat_id: chat.id, text: message, disable_web_page_preview: false }) : null;
    return reply(res, 200, { verified: true, sent: Boolean(sent), bot: { username: bot.username || bot.first_name || "Telegram bot" }, channel: { id: String(chat.id), title: chat.title || chat.username || channel, username: chat.username ? "@" + chat.username : undefined }, messageId: sent?.message_id, storage: "session-only" });
  } catch { return reply(res, 422, { error: "Check the token, channel and bot admin permissions" }); }
}
`;

export function buildProjectArchiveFiles(project: GeneratedProject, quality: ProjectQualityReport, gameAsset?: Uint8Array): Record<string, Uint8Array> {
  const slug = project.spec.slug;
  const reality = getProductReality(project.spec.presetId);
  const integrationManifest = {
    schemaVersion: 1,
    data: { provider: "DropsTab Public API", endpoint: project.spec.dataEndpoint, polling: false, sharedCacheSeconds: 900 },
    actions: { provider: "Drops Bot", mode: "guided official handoff", automaticExecution: false },
    ai: { provider: project.spec.brain.provider, model: project.spec.brain.model, keyIncluded: false },
    reality,
  };
  const files: Record<string, Uint8Array> = {
    "index.html": strToU8(project.html),
    "README.md": strToU8(projectReadme(project)),
    "project.json": strToU8(JSON.stringify(project.spec, null, 2)),
    "quality-report.json": strToU8(JSON.stringify(quality, null, 2)),
    "drops.config.json": strToU8(JSON.stringify(integrationManifest, null, 2)),
    "tests/smoke.mjs": strToU8(`import assert from "node:assert/strict";\nimport { readFile } from "node:fs/promises";\nconst html = await readFile(new URL("../index.html", import.meta.url), "utf8");\nassert.match(html, /data-project-kind="${project.spec.presetId}"/);\nassert.match(html, /DropsTab/);\nassert.match(html, /Drops Bot/);\nassert.doesNotMatch(html, /\\beval\\s*\\(|new Function/);\nconsole.log("Drops Studio smoke checks passed");\n`),
    "api/telegram/verify.mjs": strToU8(telegramFunction),
    "vercel.json": strToU8(JSON.stringify({ cleanUrls: true, trailingSlash: false }, null, 2)),
    "netlify.toml": strToU8(`[build]\n  publish = "."\n\n[[headers]]\n  for = "/*"\n  [headers.values]\n    X-Content-Type-Options = "nosniff"\n`),
    "wrangler.toml": strToU8(`name = "${slug}"\ncompatibility_date = "2026-07-28"\n[assets]\ndirectory = "."\n`),
    ".github/workflows/pages.yml": strToU8(`name: Deploy static site to Pages\non:\n  push:\n    branches: [main]\n  workflow_dispatch:\npermissions:\n  contents: read\n  pages: write\n  id-token: write\njobs:\n  deploy:\n    environment:\n      name: github-pages\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/configure-pages@v5\n      - uses: actions/upload-pages-artifact@v3\n        with:\n          path: .\n      - uses: actions/deploy-pages@v4\n`),
  };
  if (project.spec.presetId === "crypto-game" && gameAsset?.length) {
    files["assets/market-catcher-retro.png"] = gameAsset;
  }
  return files;
}

export function createProjectArchive(project: GeneratedProject, quality: ProjectQualityReport, gameAsset?: Uint8Array): Uint8Array {
  return zipSync(buildProjectArchiveFiles(project, quality, gameAsset), { level: 6 });
}
